language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-bcbbd656
    - '.*intel.+'

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
branches:
  only:
    - master

#before_install
#install
#before_script

script: ./gradlew assembleDebug

#after_success or after_failure
#after_script