language: android
android:
  components:
    - build-tools-19.1.0
    - android-19
    - sysimg-19
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
branches:
  only:
    - master

before_install:
  - android list sdk --no-ui --all --extended

#install

#before_script

script:
  - ./gradlew assembleDebug

#after_success or after_failure

#after_success:
#  - 成果物のapkを、特定のURLへアップロードする。
#  => apkは、常に保存しておけるわけではない。特定の領域に保存する、という対応が必要。

#after_script