language: android
android:
  components:
    - build-tools-21.1.2
    - android-21
    - sysimg-21
    - extra-android-support
  licenses:
    - android-sdk-license-5be876d5 # new license!
    - '.*intel.+'

# blacklist
#branches:
#  except:
#    - legacy
#    - experimental

# whitelist
branches:
  only:
    - master

before_install:
  - android list sdk --no-ui --all --extended

#install

#before_script

script:
  - ./gradlew assembleDebug

#after_success or after_failure

#after_success:
#  - upload apk files to somewhere (We should integrate other storage service or deploygate, for example.)

#after_script

